add support to cmn_fassert in linting randomize()
Lightelligence/draconian_uvm pull request #1
Opened 2022-07-19 18:55 UTC by guoqilu

2022-07-19 19:13 UTC, wstucker requested changes
Looks good, please just add another testcase which exercises correct usage of a randomize call wrapped in fassert.

2022-07-19 19:13 UTC, wstucker commented on tests/test_assert_randomize.py
> +            iut.error.assert_called_with(mock.ANY, mock.ANY, mock.ANY, "Randomize call was not wrapped with a `cmn_assert|`cmn_fassert.")
@guoqilu Please add a new testcase which covers a correct usage of randomize with cmn_fassert.

2022-07-19 19:42 UTC, ciglass requested changes

2022-07-19 19:42 UTC, ciglass commented on duvm/assert_randomize.py
> +                self.error(line_no, line, "Randomize call was not wrapped with a `cmn_assert|`cmn_fassert.")
Could you change this to be:
```suggestion
                self.error(line_no, line, "Randomize call was not wrapped with a `cmn_assert or a `cmn_fassert.")
```

I think it's a little more readable for a user seeing this message.

2022-07-27 16:56 UTC, closed without merging

2022-07-27 16:58 UTC, guoqilu commented
close this one and made a new PR:
https://github.com/Lightelligence/draconian_uvm/pull/6